CREATE TABLE PROVINCES (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE towns (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    postal_code VARCHAR(10) NOT NULL,
    id_province INT,
    FOREIGN KEY (id_province) REFERENCES PROVINCES(id) ON DELETE SET NULL
);

CREATE TABLE COMPANIES (
    id SERIAL PRIMARY KEY,
    cif VARCHAR(255) NOT NULL UNIQUE,
    business_name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    email VARCHAR(255),
    id_town INT,
    address VARCHAR(255) NOT NULL,
    FOREIGN KEY (id_town) REFERENCES TOWNS(id) ON DELETE SET NULL
);

CREATE TABLE PERMISSIONS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE ROLES (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE ROLES_PERMISSIONS (
    id_role INT NOT NULL,
    id_permission INT NOT NULL,
    PRIMARY KEY (id_role, id_permission),
    FOREIGN KEY (id_role) REFERENCES ROLES(id) ON DELETE CASCADE,
    FOREIGN KEY (id_permission) REFERENCES PERMISSIONS(id) ON DELETE CASCADE
);

CREATE TABLE ROUTES (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    route JSON NOT NULL
);

CREATE TABLE USERS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    login VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    register DATE NOT NULL DEFAULT CURRENT_DATE,
    id_company INT NOT NULL,
    id_role INT NOT NULL,
    FOREIGN KEY (id_company) REFERENCES COMPANIES(id) ON DELETE CASCADE,
    FOREIGN KEY (id_role) REFERENCES ROLES(id) ON DELETE SET NULL
);

CREATE TABLE USERS_ROUTES (
    id_user INT NOT NULL,
    id_route INT NOT NULL,
    PRIMARY KEY (id_user, id_route),
    FOREIGN KEY (id_user) REFERENCES USERS(id) ON DELETE CASCADE,
    FOREIGN KEY (id_route) REFERENCES ROUTES(id) ON DELETE CASCADE
);